FROM ubuntu:14.04

ENV DEBIAN_FRONTEND noninteractive
ENV GOPATH /opt/go

RUN apt-get update -yqq
RUN apt-get install -yqq software-properties-common curl git mercurial ruby-dev gcc make wget
RUN gem install fpm
RUN wget https://storage.googleapis.com/golang/go1.6.2.linux-amd64.tar.gz
RUN tar -C /usr/local -xzf go1.6.2.linux-amd64.tar.gz

ENV PATH /usr/local/go/bin:$PATH

ADD . /opt/go/src/github.com/seomoz/roger-bamboo

WORKDIR /opt/go/src/github.com/seomoz/roger-bamboo

RUN go version && \
    go get github.com/tools/godep && \
    go get -t github.com/smartystreets/goconvey && \
    cp -r Godeps/_workspace/src/* /opt/go/src/ && \
    /opt/go/bin/godep go build

RUN mkdir -p /output
VOLUME /output

ENV USER root
CMD builder/build.sh && mv builder/bamboo*.deb /output
